name: Kotlin Lint and Format Check

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: "graalvm"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Java version
        run: java -version

      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.45.2/ktlint
          chmod a+x ktlint

      - name: Run ktlint format
        run: ./ktlint -F "src/**/*.kt"
